version: '3.1'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=ggrelaxi
      - POSTGRES_PASSWORD=251288
    ports:
      - 9000:5432
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=ggrelaxi@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=251288
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports: 
      - 9001:80
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    name: bridge-mock-shop
    driver: bridge

volumes:
  postgres:
  pgadmin:
